### ISSUE TITLE
'text' column in plans.csv during setup

### ISSUE THREAD

**Issue by alexander-griffen** [mysociety/caps#423]
Whilst setting up the development environment, the following error is raised whilst running `./manage.py postprocess`:
```
removing internal data
Traceback (most recent call last):
  File "/workspaces/caps/./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/workspaces/caps/caps/management/commands/postprocess.py", line 76, in handle
    remove_internal_data()
  File "/workspaces/caps/caps/management/commands/postprocess.py", line 18, in remove_internal_data
    df = df.drop(
  File "/usr/local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 4906, in drop
    return super().drop(
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['text'] not found in axis"
```

Upon further exploration with Sam, there's no `text` column in the local version of `plans.csv` (although there is in production).

The list of strings passed into `replace_headers()` in `preprocess.py` doesn't include `'text'`.

There is also a management command (the code for which is in `add_text.py`) that would add the text column, although the function in this file doesn't appear to get called from anywhere.

By removing `'text'` from the list of dropped column names in `postprocess.py`, the rest of the setup process appears to run correctly, however I'm not sure if this would break anything else.

**Comment by sagepe** [comment]
One thing we wondered was whether there should be a call to `add_text` in `script/update`?
